service: radiomap-backend

provider:
	
  name: aws
	
  runtime: nodejs18.x
	
  stage: dev
	
  region: us-east-1

package:
  include:
    - stations.csv

plugins:
  - serverless-domain-manager
  - serverless-offline
	
functions:
  app:
    handler: src/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

custom:
  customDomain:
    domainName: api.radiomap.ca
    basePath: ''
    createRoute53Record: false
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: rest
  serverless-offline:
    httpPort: 3001
    lambdaPort: 3003
    noPrependStageInUrl: true

	
  